=== Staniel99/rest/Telemetry/telemetry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.telemetry.org" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="telemetry" type="tel:telemetryType" xmlns:tel="http://www.telemetry.org"/>
  <xs:complexType name="telemetryDataType">
    <xs:sequence>
      <xs:element type="xs:int" name="idTelemetryData"/>
      <xs:element type="xs:double" name="latitude"/>
      <xs:element type="xs:double" name="longitude"/>
      <xs:element type="xs:double" name="speed"/>
      <xs:element type="xs:double" name="capacity"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="telemetryDataListType">
    <xs:sequence>
      <xs:element type="tel:telemetryDataType" name="telemetryData" maxOccurs="unbounded" minOccurs="0" xmlns:tel="http://www.telemetry.org"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="carType">
    <xs:sequence>
      <xs:element type="xs:int" name="idCar"/>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="typ"/>
      <xs:element type="tel:telemetryDataListType" name="telemetryDataList" xmlns:tel="http://www.telemetry.org"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="carsType">
    <xs:sequence>
      <xs:element type="tel:carType" name="car" maxOccurs="unbounded" minOccurs="0" xmlns:tel="http://www.telemetry.org"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="telemetryType">
    <xs:sequence>
      <xs:element type="tel:carsType" name="cars" xmlns:tel="http://www.telemetry.org"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Staniel99/rest/Telemetry/telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<telemetry xmlns="http://www.telemetry.org"
           xmlns:xsdi="http://www.w3.org/2001/XMLSchema-instance"
           xsdi:schemaLocation="http://www.telemetry.org telemetry.xsd">
	<cars>
		<car>
			<idCar>1</idCar>
			<name>VW</name>
			<typ>Golf</typ>
			<telemetryDataList>
				<telemetryData>
					<idTelemetryData>1</idTelemetryData>
					<latitude>0</latitude>
					<longitude>1</longitude>
					<speed>100</speed>
					<capacity>30</capacity>
				</telemetryData>
				<telemetryData>
					<idTelemetryData>2</idTelemetryData>
					<latitude>0</latitude>
					<longitude>1</longitude>
					<speed>130</speed>
					<capacity>23</capacity>
				</telemetryData>
			</telemetryDataList>
		</car>
		<car>
			<idCar>2</idCar>
			<name>VW</name>
			<typ>Polo</typ>
			<telemetryDataList>
				<telemetryData>
					<idTelemetryData>1</idTelemetryData>
					<latitude>0</latitude>
					<longitude>1</longitude>
					<speed>100</speed>
					<capacity>30</capacity>
				</telemetryData>
				<telemetryData>
					<idTelemetryData>2</idTelemetryData>
					<latitude>0</latitude>
					<longitude>1</longitude>
					<speed>90</speed>
					<capacity>32</capacity>
				</telemetryData>
			</telemetryDataList>
		</car>
	</cars>			
</telemetry>
