=== Staniel99/rest/FahrzeugTelematik/data/carTelemetry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.cartelemetry.org" xmlns="http://www.cartelemetry.org">
  <xs:element name="carTelemetry" type="carTelemetryType"/>
  <xs:complexType name="telemetryDataType">
    <xs:sequence>
      <xs:element name="idTelemetryData" type="xs:int"/>
      <xs:element name="latitude" type="xs:double"/>
      <xs:element name="longitude" type="xs:double"/>
      <xs:element type="xs:string" name="speed"/>
      <xs:element name="capacity" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="telemtryDataListType">
    <xs:sequence>
      <xs:element type="telemetryDataType" name="telemetryData" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="carType">
    <xs:sequence>
      <xs:element type="xs:int" name="idCar"/>
      <xs:element type="xs:string" name="name"/>
      <xs:element name="type" type="xs:string"/>
      <xs:element type="telemtryDataListType" name="telemtryDataList"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="carsType">
    <xs:sequence>
      <xs:element type="carType" name="car" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="carTelemetryType">
    <xs:sequence>
      <xs:element type="carsType" name="cars"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Staniel99/rest/FahrzeugTelematik/data/data.xml
<carTelemetry xmlns="http://www.cartelemetry.org"
              xmlns:xsdi="http://www.w3.org/2001/XMLSchema-instance"
              xsdi:schemaLocation="http://www.emobility.org carTelemetry.xsd">
    <cars>
        <car>
            <idCar>1</idCar>
            <name>Tesla</name>
            <type>Model X</type>
            <telemtryDataList>
                <telemetryData>
                    <idTelemetryData>1</idTelemetryData>
                    <latitude>0</latitude>
                    <longitude>1</longitude>
                    <speed>110</speed>
                    <capacity>30</capacity>
                </telemetryData>
                <telemetryData>
                    <idTelemetryData>2</idTelemetryData>
                    <latitude>0.1</latitude>
                    <longitude>1.1</longitude>
                    <speed>110</speed>
                    <capacity>38</capacity>
                </telemetryData>
            </telemtryDataList>
        </car>
        <car>
            <idCar>2</idCar>
            <name>Tesla</name>
            <type>Model S</type>
            <telemtryDataList>
                <telemetryData>
                    <idTelemetryData>1</idTelemetryData>
                    <latitude>0</latitude>
                    <longitude>1</longitude>
                    <speed>110</speed>
                    <capacity>50</capacity>
                </telemetryData>
                <telemetryData>
                    <idTelemetryData>2</idTelemetryData>
                    <latitude>0.1</latitude>
                    <longitude>1.1</longitude>
                    <speed>110</speed>
                    <capacity>30</capacity>
                </telemetryData>
            </telemtryDataList>
        </car>
    </cars>
</carTelemetry>
